Clean up build and demo
Signed-off-by: Flynn <flynn@buoyant.io>

diff --git a/2-15-mesh-expansion/bin/bootstrap-spire b/2-15-mesh-expansion/bin/bootstrap-spire
--- a/2-15-mesh-expansion/bin/bootstrap-spire
+++ b/2-15-mesh-expansion/bin/bootstrap-spire
@@ -22,6 +22,17 @@ if [ -z "$SPIFFE_ID" ]; then
   exit 1
 fi
 
+# We also need to have a mounted /opt/spire/certs with ca.crt and ca.key in it.
+if [ ! -f /opt/spire/certs/ca.crt ]; then
+  echo "/opt/spire/certs/ca.crt is missing" >&2
+  exit 1
+fi
+
+if [ ! -f /opt/spire/certs/ca.key ]; then
+  echo "/opt/spire/certs/ca.key is missing" >&2
+  exit 1
+fi
+
 echo "==== starting SPIRE server"
 spire-server run -config ./server.cfg &
 
